server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  redis:
    port: 6379
    host: localhost
  cloud:
    gateway:
      discover:
        locator:
          enabled: true
      routes:
        # book-service load balancing
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**

        # employee-service load balancing
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - KeyAuthFilter
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true

apiKey: seandeptrai